### PR TITLE
micromagnetics implementation of Spirit

### PR DESCRIPTION
**Pull request by DTolm**
### First time contributor checklist

- [x] I have read the [README](https://github.com/spirit-code/spirit/blob/develop/README.md)
- [x] I have read the [CONTRIBUTING](https://github.com/spirit-code/spirit/blob/develop/docs/CONTRIBUTING.md) document

### Contributor checklist

- [x] I have branched from the `develop` branch
- [x] My commits are in nice logical chunks
- [x] My contribution is fully baked and is ready to be merged as is **or**
      I have cleanly laid out what this pull request should achieve in the end

------------------------------

### CODE REVIEW

**Comment by DTolm** [comment]
micromagnetics implementation of Spirit

**Comment by DTolm** [comment]
micromagnetics implementation of Spirit

**Comment by MSallermann** [comment]
Due to the many conflicts, we have decided to adopt these changes on a fresh branch. Your commit
See 67a100e1963d54895ff8e63f68d2d7034976633f, f51028c5aa451c1463dc4c9a6cb66f6cfc130243, d9cd626600e81a204baae9ba7b5806404f881dc6, da0838f8a87050f3e0698097b28027651f3101fa. Thanks!

**Comment by GPMueller** [comment]
Note: branch 'fixed-micromagnetic', starting with a3ea266bfa1d60276e16b11a7065b7b1a515fea4, see PR #599.

**Pull request closed without merging**
